### ISSUE TITLE
Nokogiri friendly signing and verification interface

### ISSUE THREAD

**Issue by jch** [benoist/xmldsig#15]
I'd like to propose a nokogiri mixin to provide an alternative interface for XML signing and verification.

`Xmldsig::SignedDocument` expects an XML string in it's constructor, which it builds into a `Nokogiri::XML::Document` object. Sometimes I already have a `Nokogiri::XML::Document` object in memory, and would like to modify that instance, rather than doing wasteful work calling `to_s` and parsing it back into memory again. My fix was to copy out a piece of the implementation and use `Xmldsig::Signature` directly:

```ruby
# document is an existing Nokogiri::XML::Document
document.xpath("//ds:Signature", Xmldsig::NAMESPACES).reverse.each do |element|
  signature = Xmldsig::Signature.new(element)

  # add ds:X509Certificate
  encoded_certificate = Base64.encode64(options[:certificate].to_s).chomp
  signature.signature.at_xpath("descendant::ds:X509Certificate", Xmldsig::NAMESPACES).content = encoded_certificate

  # add ds:SignatureValue
  signature.sign(options[:private_key])
end
```

This gave me the initial idea to update `SignedDocument`'s initialize method to take either a `String` or a `Nokogiri::XML::Document` object. But thinking about it more, it feels natural to be able to sign `Nokogiri::XML::Node` objects directly. For example, the interface may look like this:

```ruby
# template of signature fragment. This can be added anywhere in a document.
signature_template = Nokogiri::XML.fragment "<ds:Signature>...</ds:Signature>"

document = Nokogiri::XML("<Document />")  # some document already in memory
document.add_child(signature_template.dup)

private_key = OpenSSL::PKey::RSA.new ...
certificate = OpenSSL::X509::Certificate.new ...

# this finds all `Signature` elements and signs them
document.sign(:private_key => private_key, :certificate => certificate)

# alternatively, you could sign a specific element
document.at_xpath("/Document/ds:Signature").sign(:private_key => private_key)

# verification works much the same way
document.verify(:certificate => certificate)

# iterate through each signature and verify
document.signatures.each do |sig|
  sig.verify(:certificate => certificate)
end
```

@benoist what do you think of this idea? Do you think it would be a useful addition to this gem, or is it out of scope and better served as a separate gem? I've started spiking out a separate gem, [nokogiri-signatures](https://github.com/jch/nokogiri-signatures), but wanted to hear your feedback.

Thanks for building and maintaining this great gem!

**Comment by benoist** [comment]
@jch I agree that it should be allowed to use an existing nokogiri document when signing.
Perhaps it might be better to remove the signing features from the signed document class and introduce a new unsigned document class. The initializer for UnsignedDocument should take a string of XML or a in memory Nokogiri::XML::Document. The reason for using whole documents instead of fragments, is because of the canonicalization on the document. When verifying signatures, the whitespace needs to be exactly the same as it was when signing. Allowing fragments to be signed and be added in another XML node might change the indentation, which will break the signature. 

Creating a mixin for Nokogiri::XML::Document looks really nice, but I'm not sure if it's a good thing to support without the help of the Nokogiri maintainers.

**Comment by jch** [comment]
> The reason for using whole documents instead of fragments, is because of the canonicalization on the document. When verifying signatures, the whitespace needs to be exactly the same as it was when signing. Allowing fragments to be signed and be added in another XML node might change the indentation, which will break the signature.

:+1: this makes sense to me. I also ran into this first hand in our production app, and had to use `document.to_xml(:save_with => 0)` to preserve whitespace. I'll whip together a PR and move discussion over to that.

**Comment by benoist** [comment]
PR is merged. Closing this issue
