### ISSUE TITLE
ID attribute location

### ISSUE THREAD

**Issue by mjurin** [benoist/xmldsig#27]
Hi,

I have a quick question :). The gem works great, but for a project I need to put the ID attribute on the first child instead of the root element.

If I edit your example:
```    
<foo:Foo ...>
   <foo:Bar ID="foo">bar</foo:Bar>
     ...other stuff
```
So basically the ID went to the foo:Bar node. Is there a quick way to change this? (Also I would need to call the attribute Id instead of ID).

Thanks,
Marko

**Comment by benoist** [comment]
Where do you have the signature element?

**Comment by mjurin** [comment]
Thanks for the quick response.
Same level as foo:bar
```
<foo:Foo  xmlns:foo="http://example.com/foo#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#">
  <foo:Bar ID="foo">bar</foo:Bar>
  <ds:Signature>...</ds:Signature>
</foo:Foo>
```

**Comment by benoist** [comment]
ok, make sure you leave out the enveloped signature transform. And you can specify the attribute type when signing.

signed_document = Xmldsig::SignedDocument.new(signed_xml, id_attr: "MyID")
signed_document.validate(certificate)

**Comment by mjurin** [comment]
It works!

Thanks for the quick support.

Closing the issue.

Best regards,
Marko
