### ISSUE TITLE
Why ReferencedNodeNotFound isn't subclass of Xmldsig::Error ?

### ISSUE THREAD

**Issue by nov** [benoist/xmldsig#52]
I found `Xmldsig::Reference::ReferencedNodeNotFound` is subclass of `Exception` not `StandardError` nor `Xmldsig::Error`.

I've expected `rescue Xmldsig::Error` catches all errors occured in this gem, but only that error wasn't caught.

Is it intended behavior?

**Comment by benoist** [comment]
I don't remember, but looking at the code, I don't see a reason why it should be Exception.
It can be replaced by Xmldsig::Error

**Comment by nov** [comment]
OK, I've made a PR for that.

**Comment by benoist** [comment]
Version 0.7.0 is released
